include_recipe "cookbook-qubell-tomcat"
include_recipe "cookbook-qubell-zookeeper"
include_recipe "cookbook-qubell-solr"
include_recipe "cookbook-qubell-solr::create_collection"
include_recipe "minitest-handler"
